let fn_uat_mlp_svfn_dom_resumen_status = (startTime:datetime, endTime:datetime) {
    let fuente_notpii_interpolated = toscalar(fn_uat_mlp_svfn_dom_fuente_notpii_interpolated_status(startTime, endTime));
    let tags = toscalar(fn_uat_mlp_svfn_dom_tags_status(startTime, endTime));
    let transformacion = toscalar(fn_uat_mlp_svfn_dom_transformacion_status(startTime, endTime));
    let prediccion = toscalar(fn_uat_mlp_svfn_dom_prediccion_status(startTime, endTime));
    let status = iff(
        fuente_notpii_interpolated == "ALERT" or tags == "ALERT" or transformacion == "ALERT" or prediccion == "ALERT",
        "ALERT",
        "OK"
    );
    print status
};
