let fn_src_mlp_uat_ws_appservicehttps = (appServiceName:string, startTime:datetime, endTime:datetime) {
(
      workspace("/subscriptions/0d996eb2-802f-4ef8-8ae6-d385c74da7e6/resourceGroups/ams-uat-dataplatform-rg/providers/Microsoft.OperationalInsights/workspaces/ams-uat-dataplatform-laws").table("AppServiceHTTPLogs")
      | where TimeGenerated between (startTime .. endTime)
      | where Referer has appServiceName
    )
};