let fn_src_mlp_uat_ws_sparklogging = (sourceType:string, startTime:datetime, endTime:datetime) {
(
      workspace("subscriptions/0d996eb2-802f-4ef8-8ae6-d385c74da7e6/resourceGroups/ams-uat-dataplatform-rg/providers/Microsoft.OperationalInsights/workspaces/ams-uat-dataplatform-laws").table("SparkLoggingEvent_CL")
      | where TimeGenerated between (startTime .. endTime)
      | where log_logger_s == sourceType
    )
};