let fn_prd_mlp_ada_dom_plans_status = (startTime:datetime, endTime:datetime) {
  let expected_job01 = toscalar(
    range ts from startTime to endTime step 1m
    | where datetime_part("minute", ts) == 46 and datetime_part("hour", ts) in (0,1,6,13,17,18,19)
    | count
  );
  let real_job01 = toscalar(
    fn_src_mlp_systemlogs_all(startTime - 25m, endTime)
    | where JobName_s == "mlp-prd-caj-plans-job01"
    | where Log_s contains "has successfully completed"
    | count
  );
  let job01_alert = iff(expected_job01 == 0, false, real_job01 < ceiling(0.85 * expected_job01));
  let lag = toscalar(fn_prd_mlp_ada_lag_helpers(dynamic([
      "planes_semanales_AXB","planes_semanales_PLANTA_CONCENTRADORA_RECUPERACION_CU","planes_semanales_LEY_CONCENTRADO_CU",
      "planes_semanales_TRANSPORTADO_STMG","planes_semanales_CONCENTRADO_PRODUCIDO","planes_semanales_PLANTA_CONCENTRADORA_LEY_CU",
      "planes_semanales_PLANTA_CONCENTRADORA_CU_FINO_PRODUCIDO","planes_semanales_PLANTA_CONCENTRADORA_MO_FINO_PRODUCIDO",
      "planes_semanales_PLANTA_CONCENTRADORA_TRATAMIENTO","planes_semanales_PUERTO_CU_FINO_FILTRADO_PAGABLE",
      "planes_acc_mensuales_TRANSPORTADO_STMG","planes_acc_mensuales_CONCENTRADO_PRODUCIDO","planes_acc_mensuales_PLANTA_CONCENTRADORA_LEY_CU",
      "planes_acc_mensuales_LEY_CONCENTRADO_CU","planes_acc_mensuales_PUERTO_CU_FINO_FILTRADO_PAGABLE",
      "planes_acc_mensuales_PLANTA_CONCENTRADORA_TRATAMIENTO","planes_acc_mensuales_EXTRACCION_MINA",
      "planes_acc_mensuales_PLANTA_CONCENTRADORA_CU_FINO_PRODUCIDO","planes_acc_mensuales_PLANTA_CONCENTRADORA_MO_FINO_PRODUCIDO",
      "planes_acc_mensuales_PLANTA_CONCENTRADORA_RECUPERACION_CU"
  ]), startTime, endTime));
  let status = iff(job01_alert or lag == "ALERT", "ALERT", "OK");
  print status 
};
