let fn_prd_mlp_ada_dom_blockgrade_status = (startTime:datetime, endTime:datetime) {
  let ing_ok = toscalar(
    fn_src_mlp_pipeline_runs_all(startTime - 60m, endTime)
    | where ResourceGroup == "MLP-PRD-RG-BLKGRDE" // filtro temprano por dominio
    | where Category == "PipelineRuns"
    | where OperationName in ("PL_FULL - Succeeded", "PL_BLOCKGRADE - Succeeded")
    | count
  ) > 0;
  let lag = toscalar(fn_prd_mlp_ada_lag_helpers(dynamic(["blockgrade_bybucket"]), startTime, endTime));
  let en_mantencion = toscalar(fn_prd_mlp_ada_en_mantencion(startTime, endTime) | project en_mantencion);
  let status = iff(en_mantencion, "OK", iff(not(ing_ok) or lag == "ALERT", "ALERT", "OK"));
  print status = status
};
