let fn_prd_mlp_pdm_caex_dom_fuente_horometros_status = (startTime:datetime, endTime:datetime) {
    let umbral = toscalar(fn_prd_mlp_pdm_caex_umbrales_fuentes() | where fuente == 'HOROMETROS' | project umbral_min);
    SparkLoggingEvent_CL
    | where TimeGenerated between (startTime .. endTime)
    | where log_logger_s == 'PDM_CAEX'
    | where Message has 'HOROMETROS'
    | summarize arg_max(TimeGenerated, Message)
    | extend json_msg = parse_json(Message)
    | extend json_msg = parse_json(Message)
    | extend
        ultimo_timestamp_fuente = datetime_local_to_utc(todatetime(json_msg.ultimo_timestamp), "America/Santiago"),
        cantidad_registros      = json_msg.registros,
        estado                  = json_msg.estado,
        tabla                   = json_msg.tabla,
        fuente                  = tostring(json_msg.fuente)
    | extend Diferencia_Minutos = datetime_diff("minute", now(), ultimo_timestamp_fuente)
    | project fuente, tabla, ultimo_timestamp_fuente, cantidad_registros, Diferencia_Minutos
    | join kind=inner fn_prd_mlp_pdm_caex_umbrales_fuentes on fuente
    // parseo de umbrales
    | extend umbral = toint(umbral)
    | extend sobre_umbral = Diferencia_Minutos > umbral
    | project fuente, status = iff(sobre_umbral, "ALERT", "OK")
};
