let fn_prd_mlp_pdm_caex_dom_resumen_status = (startTime:datetime, endTime:datetime) {
    let fuentes = toscalar(fn_prd_mlp_pdm_caex_dom_fuentes_status(startTime, endTime) | project Estado);
    let jobs = toscalar(fn_prd_mlp_pdm_caex_dom_jobs_status(startTime, endTime) | project Estado);
    let emails = toscalar(fn_prd_mlp_pdm_caex_dom_emails_status(startTime, endTime) | project Estado);
    print Fuentes = fuentes, Jobs_Dominio = jobs, Envio_Emails = emails
    | extend Estado = iff(Fuentes == 'Alertar' or Jobs_Dominio == 'Alertar' or Envio_Emails == 'Alertar', 'Alertar', 'No Alertar');
};
