let fn_prd_mlp_pdm_caex_dom_fuente_horometros_status = (startTime:datetime, endTime:datetime) {
    SparkLoggingEvent_CL
    | where TimeGenerated between (startTime .. endTime)
    | where log_logger_s == 'PDM_CAEX'
    | where Message has 'HOROMETROS'
    | summarize arg_max(TimeGenerated, Message)
    | extend json_msg = parse_json(Message)
    | extend ultimo_timestamp_fuente = datetime_local_to_utc(todatetime(json_msg.ultimo_timestamp), 'America/Santiago')
    | extend Diferencia_Minutos = datetime_diff('minute', now(), ultimo_timestamp_fuente)
    | project fuente = 'HOROMETROS', umbral_min = 10080, Diferencia_Minutos, status = iff(Diferencia_Minutos > 10080, 'ALERT', 'OK')
    | union (datatable(fuente:string, umbral_min:int, Diferencia_Minutos:long, status:string)['HOROMETROS', 10080, long(0), 'OK'])
    | take 1
};
