let fn_prd_mlp_ada_amg_dom_settings_status = (startTime:datetime, endTime:datetime) {
  let expected_job01 = toscalar(
    range ts from startTime to endTime step 1m
    | where datetime_part("minute", ts) == 0
    | count
  );
  let expected_job02 = toscalar(
    range ts from startTime to endTime step 1m
    | where datetime_part("minute", ts) == 0 and datetime_part("hour", ts) in (12,18)
    | count
  );
  let real_job01 = toscalar(
    fn_src_mlp_ws_prfci("ContainerAppSystemLogs_CL", startTime - 4h, endTime)
    | where TimeGenerated >= startTime - 4h and TimeGenerated < endTime
    | where JobName_s == "mlp-prd-caj-prfci-job01"
    | where Log_s contains "has successfully completed"
    | count
  );
  let real_job02 = toscalar(
    fn_src_mlp_ws_prfci("ContainerAppSystemLogs_CL", startTime - 4h, endTime)
    | where TimeGenerated >= startTime - 4h and TimeGenerated < endTime
    | where JobName_s == "mlp-prd-caj-prfci-job02"
    | where Log_s contains "has successfully completed"
    | count
  );
  let job01_alert = iff(expected_job01 == 0, false, real_job01 == 0);
  let job02_alert = iff(expected_job02 == 0, false, real_job02 == 0);
  let status = iff(job01_alert or job02_alert, "ALERT", "OK");
  print status
};
