  union isfuzzy=true
    (
      workspace("/subscriptions/c68213bf-7453-4ba4-9aaa-56b822af4c20/resourceGroups/MLP-PRD-RG-PRFCI/providers/Microsoft.OperationalInsights/workspaces/mlp-prd-law-prfci").table("ContainerAppSystemLogs_CL")
      | where TimeGenerated between (startTime .. endTime)
      | where sourceType == "ContainerAppSystemLogs_CL"
      | extend source_table = "ContainerAppSystemLogs_CL"
    )
