// Estado de mantención operacional ADA basado en CH-1 / CH-02.
let fn_prd_mlp_ada_en_mantencion = (startTime:datetime, endTime:datetime) {
  fn_src_mlp_ws_dataplatform("Logs_MLP_ADA_CL", startTime, endTime)
  | where product_origin == "DISPATCH_CONDICION_OPERACIONAL"
  | top 1 by TimeGenerated desc
  | extend CH1 = tostring(detail["CH-1"]), CH2 = tostring(detail["CH-02"])
  | extend en_mantencion = iff(trim(" ", tolower(CH1)) != "efectivo" or trim(" ", tolower(CH2)) != "efectivo", true, false)
  | project en_mantencion
};
